#ifndef _HW_CONF_H_
#define _HW_CONF_H_

#define MOTOR_DRIVER_1_PWM_DEV PWMD5
#define MOTOR_DRIVER_1_FWD_CH 3
#define MOTOR_DRIVER_1_REV_CH 2
#define MOTOR_DRIVER_2_PWM_DEV PWMD4
#define MOTOR_DRIVER_2_FWD_CH 3
#define MOTOR_DRIVER_2_REV_CH 4
#define MOTOR_DRIVER_3_PWM_DEV PWMD1
#define MOTOR_DRIVER_3_FWD_CH 2
#define MOTOR_DRIVER_3_REV_CH 3
#define MOTOR_DRIVER_4_PWM_DEV PWMD12
#define MOTOR_DRIVER_4_FWD_CH 1
#define MOTOR_DRIVER_4_REV_CH 2

#endif /* _HW_CONF_H_ */
