#ifndef _HW_CONF_H_
#define _HW_CONF_H_

#include "hal.h"

#define MOTOR_DRIVER_1_PWM_DEV PWMD5
#define MOTOR_DRIVER_1_FWD_CH 2
#define MOTOR_DRIVER_1_REV_CH 1
#define MOTOR_DRIVER_1_FWD_GPIO GPIOA
#define MOTOR_DRIVER_1_FWD_PIN 2
#define MOTOR_DRIVER_1_REV_GPIO GPIOA
#define MOTOR_DRIVER_1_REV_PIN 1
#define MOTOR_DRIVER_1_AF GPIO_AF_TIM5
#define MOTOR_DRIVER_2_PWM_DEV PWMD4
#define MOTOR_DRIVER_2_FWD_CH 2
#define MOTOR_DRIVER_2_REV_CH 3
#define MOTOR_DRIVER_2_FWD_GPIO GPIOB
#define MOTOR_DRIVER_2_FWD_PIN 8
#define MOTOR_DRIVER_2_REV_GPIO GPIOB
#define MOTOR_DRIVER_2_REV_PIN 9
#define MOTOR_DRIVER_2_AF GPIO_AF_TIM4
#define MOTOR_DRIVER_3_PWM_DEV PWMD1
#define MOTOR_DRIVER_3_FWD_CH 1
#define MOTOR_DRIVER_3_REV_CH 2
#define MOTOR_DRIVER_3_FWD_GPIO GPIOA
#define MOTOR_DRIVER_3_FWD_PIN 9
#define MOTOR_DRIVER_3_REV_GPIO GPIOA
#define MOTOR_DRIVER_3_REV_PIN 10
#define MOTOR_DRIVER_3_AF GPIO_AF_TIM1
#define MOTOR_DRIVER_4_PWM_DEV 12
#define MOTOR_DRIVER_4_FWD_CH 0
#define MOTOR_DRIVER_4_REV_CH 1
#define MOTOR_DRIVER_4_FWD_GPIO GPIOB
#define MOTOR_DRIVER_4_FWD_PIN 14
#define MOTOR_DRIVER_4_REV_GPIO GPIOB
#define MOTOR_DRIVER_4_REV_PIN 15
#define MOTOR_DRIVER_4_AF 9

#define IMU_I2C_DEV I2CD1
#define IMU_SCL_GPIO GPIOB
#define IMU_SCL_PIN 6
#define IMU_SDA_GPIO GPIOB
#define IMU_SDA_PIN 7

#define I2C_DEV I2CD2
#define SCL_GPIO GPIOB
#define SCL_PIN 10
#define SDA_GPIO GPIOB
#define SDA_PIN 11

#define SCK_GPIO GPIOC
#define SCK_PIN 10
#define MISO_GPIO GPIOC
#define MISO_PIN 11
#define MOSI_GPIO GPIOC
#define MOSI_PIN 12
#define CS_GPIO GPIOA
#define CS_PIN 15
#define SPI_DEV SPID3

#define LED_GPIO GPIOA
#define LED_PIN 6

#endif /* _HW_CONF_H_ */
